create table if not exists public.news_posts (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  category text not null check (category in ('Tin tức', 'Thông báo', 'Bài chia sẻ')),
  author_name text not null default 'Ban Truyền Thông',
  excerpt text not null,
  content text[] not null default '{}',
  image_key text not null default 'church' check (image_key in ('church', 'table', 'book', 'meeting', 'retreat', 'podcast')),
  photo_url text not null,
  media_asset_id uuid references public.media_assets(id) on delete set null,
  featured boolean not null default false,
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  published_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists news_posts_status_published_idx
on public.news_posts (status, published_at desc);

create index if not exists news_posts_category_published_idx
on public.news_posts (category, published_at desc);

create index if not exists news_posts_featured_idx
on public.news_posts (featured, published_at desc)
where status = 'published';

create index if not exists news_posts_media_asset_id_idx
on public.news_posts (media_asset_id);

create index if not exists news_posts_created_by_idx
on public.news_posts (created_by);

alter table public.media_assets
drop constraint if exists media_assets_related_table_check;

alter table public.media_assets
add constraint media_assets_related_table_check
check (
  related_table in ('resources', 'assignments', 'profiles', 'events', 'news_posts')
);

drop trigger if exists news_posts_set_updated_at on public.news_posts;
create trigger news_posts_set_updated_at
before update on public.news_posts
for each row execute function public.set_updated_at();

alter table public.news_posts enable row level security;

drop policy if exists "news_posts_public_read_published" on public.news_posts;
create policy "news_posts_public_read_published"
on public.news_posts for select
to anon, authenticated
using (status = 'published');

drop policy if exists "news_posts_staff_manage" on public.news_posts;
create policy "news_posts_staff_manage"
on public.news_posts for all
to authenticated
using (public.is_staff())
with check (public.is_staff());
