create type public.user_role as enum ('member', 'teacher', 'admin');
create type public.user_status as enum ('active', 'inactive', 'blocked');
create type public.submission_status as enum ('draft', 'submitted', 'graded');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  email text not null unique,
  phone text,
  avatar_url text,
  role public.user_role not null default 'member',
  status public.user_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.resources (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null,
  url text not null,
  uploaded_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  location text not null,
  event_time timestamptz not null,
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.assignments (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  week_number integer check (week_number is null or week_number > 0),
  attachment_url text,
  due_date date,
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.submissions (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text,
  submitted_at timestamptz,
  status public.submission_status not null default 'draft',
  grade numeric(5, 2) check (grade is null or (grade >= 0 and grade <= 10)),
  feedback text,
  unique (assignment_id, user_id)
);

create table public.comments (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

create index events_event_time_idx on public.events(event_time);
create index notifications_user_created_idx on public.notifications(user_id, created_at desc);
create index assignments_due_date_idx on public.assignments(due_date);
create index submissions_user_idx on public.submissions(user_id);
create index comments_assignment_idx on public.comments(assignment_id, created_at);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger events_set_updated_at
before update on public.events
for each row execute function public.set_updated_at();

create trigger assignments_set_updated_at
before update on public.assignments
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, name, email, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    new.email,
    nullif(new.raw_user_meta_data ->> 'phone', '')
  );
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

revoke execute on function public.handle_new_user() from public, anon, authenticated;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('teacher', 'admin')
      and status = 'active'
  );
$$;

revoke execute on function public.is_staff() from public, anon;
grant execute on function public.is_staff() to authenticated;

alter table public.profiles enable row level security;
alter table public.resources enable row level security;
alter table public.events enable row level security;
alter table public.notifications enable row level security;
alter table public.assignments enable row level security;
alter table public.submissions enable row level security;
alter table public.comments enable row level security;

create policy "profiles_select_own"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_staff());

create policy "profiles_update_own"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

revoke update on public.profiles from authenticated;
grant update (name, phone, avatar_url, updated_at) on public.profiles to authenticated;

create policy "resources_public_read"
on public.resources for select
to anon, authenticated
using (true);

create policy "resources_staff_manage"
on public.resources for all
to authenticated
using (public.is_staff())
with check (public.is_staff());

create policy "events_public_read"
on public.events for select
to anon, authenticated
using (true);

create policy "events_staff_manage"
on public.events for all
to authenticated
using (public.is_staff())
with check (public.is_staff());

create policy "notifications_own"
on public.notifications for select
to authenticated
using (user_id = auth.uid());

create policy "notifications_own_update"
on public.notifications for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "notifications_staff_insert"
on public.notifications for insert
to authenticated
with check (public.is_staff());

create policy "assignments_authenticated_read"
on public.assignments for select
to authenticated
using (true);

create policy "assignments_staff_manage"
on public.assignments for all
to authenticated
using (public.is_staff())
with check (public.is_staff());

create policy "submissions_select_own_or_staff"
on public.submissions for select
to authenticated
using (user_id = auth.uid() or public.is_staff());

create policy "submissions_insert_own"
on public.submissions for insert
to authenticated
with check (user_id = auth.uid());

create policy "submissions_update_own_or_staff"
on public.submissions for update
to authenticated
using (user_id = auth.uid() or public.is_staff())
with check (user_id = auth.uid() or public.is_staff());

create policy "comments_authenticated_read"
on public.comments for select
to authenticated
using (true);

create policy "comments_insert_own"
on public.comments for insert
to authenticated
with check (user_id = auth.uid());

create policy "comments_delete_own_or_staff"
on public.comments for delete
to authenticated
using (user_id = auth.uid() or public.is_staff());
